### ISSUE TITLE
Username and password got lost in the process

### ISSUE THREAD

**Issue by nickhowston** [jwcook23/mssql_dataframe#40] opened 2023-09-26 12:37 UTC
Hello,

First of all, thank you so much for making this package, the upsert feature is exactly what I am looking for!

I am having a strange issue when using it, I am not 100% sure it's an error from this package, but I hope with your experience you would help me understanding the problem better.

My server is MSSQL that's deployed on Azure, I make the connection in the standard way:
```
sql = SQLServer(
            database="database_name",
            server="tcp:servername.database.windows.net,1433",
            username="username",
            password="password")
```

The connection can be established locally, it works perfectly. But once I publish the code on Azure Function, the connection cannot be established and will return an error Error: 18456, Severity: 14, State: 122. The username is empty "". 

It is obvious that this error has something to do with the environment where Azure function runs, but it's also strange that the username got lost inside SQLServer(), which should not be affected by running envrionment. The only place that I suspect might be the cause is in connect.py line 74-81

```
self.connection = pyodbc.connect(
                driver=self.connection_spec["driver"],
                server=self.connection_spec["server"],
                database=self.connection_spec["database"],
                autocommit=False,
                UID=username,
                PWD=password,
            )
```

If the keywords UID PWD are not recognized, then maybe the username is not passed down? I saw from the doc that pyodbc use keywords 'user' 'password' [https://github.com/mkleehammer/pyodbc/wiki/The-pyodbc-Module#connect]

I hope you would be willing to share some insights  regarding this :) Thanks a lot!

**Comment by jwcook23** [comment] 2023-09-26 21:41
Hi @nickhowston. Thank you for taking interest in mssql_dataframe.

You are correct that the issue is due to the version differences. In version 3, kwargs are passed directly to pyodbc for the connection. You will need to pass the keywords UID and PWD as these are needed to pyodc. For example:

`sql = SQLServer(database='database', server='server', UID='username', PWD='password')`

In version 2, I had these explicitly named differently in SQLServer and connect, but decided it would be better to pass everything directly to pyodbc for flexibility. Any keyword pyodbc can use for the connection should be acceptable now.

https://github.com/mkleehammer/pyodbc/wiki/The-pyodbc-Module#connect

I should better document this and raise appropriate exceptions.

**Comment by nickhowston** [comment] 2023-09-27 13:13
Hi @jwcook23, thanks for your reply. I used to use sqlalchemy in combination with pandas.to_sql() to handle bulk insert to MSSQL but update has always been a pain, this module would definitely makes my life easier.

Did you change the keywords to UID and PWD because of some changes in pyodbc? I have changed back to 2.0.1 version and now I can connect to SQLServer again. The pyodbc version on my local machine and Azure is the same 4.0.39, It seems that the module failed to convert to correct keywords during the process.

Strangely for the same insert function, it works locally but fails when I run it from an Azure Function App environment, I am trying to figure out why error would occur because connection is already successfully established by this step:
```
    sql.write.insert(
        target_table_name,
        dataframe
    )
```

**Comment by nickhowston** [comment] 2023-09-27 18:08
Hi @jwcook23, I understand now, then it's interesting that version 3 doesn't work in my case.

As for the sql.write.insert(), sorry I have tried to catch the error message with try except, but strangely no Exception was returned, the process just failed at this step. Do you think this might be caused by different ODBC versions? I'll share with you more details once I can find an error message.

**Comment by nickhowston** [comment] 2023-10-02 09:49
Hi @jwcook23 , I have a small update about sql.write.insert(), I found out that it failed because of the query length limit in Azure Function, which is really small (4096), the error is not cased by your module.

**Comment by jwcook23** [comment] 2023-10-03 15:13
Thank you for sharing. Is the error message clearly exposed? I would expect the pyodbc cursor.executemany method to raise some error.

**Comment by nickhowston** [comment] 2023-10-04 08:33
Strangely the error message was not exposed, I've tried to catch with in Try Except but it didn't work.

**Comment by jwcook23** [comment] 2023-10-08 10:48
Closing this issue for now. Let me know if you have any other problems.

**Closed by jwcook23** 2023-10-08 10:48 UTC
